
name: Test React Application

# This workflow builds and tests the React app in the 'client' directory
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_test_react:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]  # Using stable Node.js versions

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm ci and test
        working-directory: ./client
        run: |
          npm ci
          npm test    
      - name: Deploy to Vercel
        run: |
          cd client
          npx vercel --prod --yes --token="pLe1lR1pKMZXjCZcygVnPGAR"
        env:
          VERCEL_ORG_ID: "team_Y8kBrgEzWEUHGMwYmgqnDIlX"
          VERCEL_PROJECT_ID: "prj_nFxkNHBrYF9lpprQxKbk886u5uL0"
