name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install Root Dependencies
      run: npm ci
    
    - name: Install Client Dependencies
      working-directory: ./client
      run: |
        npm ci
        npm install react-scripts --save
    
    - name: Install Server Dependencies
      working-directory: ./server
      run: npm ci
    
    - name: Run Client Tests
      working-directory: ./client
      run: npm test -- --watchAll=false
    
    - name: Run Server Tests
      working-directory: ./server
      run: npm test
    
    - name: Build Client
      working-directory: ./client
      run: npm run build
    
    - name: Build Server
      working-directory: ./server
      run: npm run build
